"""Feature pipeline composer for orchestrating plugin execution.

This module provides the FeaturePipeline class that composes multiple feature
plugins into a single execution pipeline, handling plugin ordering, validation,
error handling, and metadata aggregation.

Example:
    ```python
    from src.features.pipeline import FeaturePipeline, PipelineConfig
    from src.features import TemporalFeaturesPlugin, LagFeaturesPlugin

    # Create pipeline with plugins
    pipeline = FeaturePipeline(
        plugins=[
            (TemporalFeaturesPlugin(), {"include_cyclical": True}),
            (LagFeaturesPlugin(), {"lag_periods": [24, 48]}),
        ],
    )

    # Generate features
    result = pipeline.run(df)
    print(f"Generated {len(result.feature_names)} features")
    print(f"Execution time: {result.execution_time_ms}ms")
    ```
"""

from __future__ import annotations

import time
from dataclasses import dataclass, field
from typing import TYPE_CHECKING, Any

import pandas as pd
from pydantic import BaseModel, ConfigDict, Field, field_validator

from src.features.base.plugin import BaseFeaturePlugin
from src.features.registry import PluginRegistry
from src.utils.logger import get_logger

if TYPE_CHECKING:
    from collections.abc import Sequence

logger = get_logger(__name__)


class PipelineError(Exception):
    """Base exception for pipeline errors.

    Attributes:
        message: Error message.
        plugin_name: Name of the plugin that caused the error.
        stage: Pipeline stage where the error occurred.
    """

    def __init__(
        self,
        message: str,
        plugin_name: str | None = None,
        stage: str | None = None,
    ) -> None:
        """Initialize PipelineError.

        Args:
            message: Error message.
            plugin_name: Name of the plugin that caused the error.
            stage: Pipeline stage where the error occurred.
        """
        self.plugin_name = plugin_name
        self.stage = stage
        super().__init__(message)


class PipelineConfigError(PipelineError):
    """Exception raised for pipeline configuration errors."""


class PipelineExecutionError(PipelineError):
    """Exception raised for errors during pipeline execution."""


class FeatureCollisionError(PipelineError):
    """Exception raised when feature name collisions are detected."""

    def __init__(self, collisions: dict[str, list[str]]) -> None:
        """Initialize FeatureCollisionError.

        Args:
            collisions: Dictionary mapping feature names to list of plugin names
                that generate them.
        """
        self.collisions = collisions
        collision_details = ", ".join(
            f"'{name}' (from: {', '.join(plugins)})"
            for name, plugins in collisions.items()
        )
        msg = f"Feature name collisions detected: {collision_details}"
        super().__init__(msg)


@dataclass
class PluginExecutionResult:
    """Result of a single plugin execution.

    Attributes:
        plugin_name: Name of the executed plugin.
        plugin_version: Version of the executed plugin.
        feature_names: List of features generated by the plugin.
        execution_time_ms: Execution time in milliseconds.
        rows_processed: Number of rows processed.
        success: Whether the execution was successful.
        error_message: Error message if execution failed.
    """

    plugin_name: str
    plugin_version: str
    feature_names: list[str]
    execution_time_ms: float
    rows_processed: int
    success: bool = True
    error_message: str | None = None


@dataclass
class PipelineResult:
    """Result of a complete pipeline execution.

    Attributes:
        df: Output DataFrame with generated features.
        feature_names: List of all generated feature names.
        plugin_results: List of individual plugin execution results.
        execution_time_ms: Total execution time in milliseconds.
        input_rows: Number of input rows.
        output_columns: Number of output columns.
        plugins_executed: Number of plugins successfully executed.
        success: Whether the entire pipeline executed successfully.
    """

    df: pd.DataFrame
    feature_names: list[str] = field(default_factory=list)
    plugin_results: list[PluginExecutionResult] = field(default_factory=list)
    execution_time_ms: float = 0.0
    input_rows: int = 0
    output_columns: int = 0
    plugins_executed: int = 0
    success: bool = True

    def get_summary(self) -> dict[str, Any]:
        """Get a summary of the pipeline execution.

        Returns:
            Dictionary with execution summary statistics.
        """
        return {
            "success": self.success,
            "plugins_executed": self.plugins_executed,
            "features_generated": len(self.feature_names),
            "execution_time_ms": round(self.execution_time_ms, 2),
            "input_rows": self.input_rows,
            "output_columns": self.output_columns,
            "plugin_details": [
                {
                    "name": r.plugin_name,
                    "version": r.plugin_version,
                    "features": len(r.feature_names),
                    "time_ms": round(r.execution_time_ms, 2),
                    "success": r.success,
                }
                for r in self.plugin_results
            ],
        }


class PipelineConfig(BaseModel):
    """Configuration for the feature pipeline.

    Attributes:
        fail_fast: Stop execution on first plugin error (default: True).
        validate_features: Validate generated features for NaN/Inf (default: True).
        detect_collisions: Check for feature name collisions (default: True).
        copy_input: Copy input DataFrame before processing (default: True).
        preserve_input_columns: Keep original columns in output (default: True).
    """

    model_config = ConfigDict(
        frozen=True,
        extra="forbid",
    )

    fail_fast: bool = Field(
        default=True,
        description="Stop execution on first plugin error",
    )
    validate_features: bool = Field(
        default=True,
        description="Validate generated features for NaN/Inf values",
    )
    detect_collisions: bool = Field(
        default=True,
        description="Check for feature name collisions before execution",
    )
    copy_input: bool = Field(
        default=True,
        description="Copy input DataFrame before processing",
    )
    preserve_input_columns: bool = Field(
        default=True,
        description="Keep original columns in output DataFrame",
    )


class PluginStep(BaseModel):
    """Configuration for a single plugin step in the pipeline.

    Attributes:
        plugin_name: Name of the plugin (for registry lookup) or instance.
        config: Plugin-specific configuration dictionary.
        enabled: Whether this step is enabled (default: True).
    """

    model_config = ConfigDict(
        arbitrary_types_allowed=True,
        extra="forbid",
    )

    plugin_name: str = Field(
        description="Name of the plugin in the registry",
    )
    config: dict[str, Any] = Field(
        default_factory=dict,
        description="Plugin-specific configuration",
    )
    enabled: bool = Field(
        default=True,
        description="Whether this step is enabled",
    )

    @field_validator("plugin_name")
    @classmethod
    def validate_plugin_name(cls, v: str) -> str:
        """Validate that plugin_name is not empty."""
        if not v or not v.strip():
            msg = "plugin_name cannot be empty"
            raise ValueError(msg)
        return v.strip()


class FeaturePipeline:
    """Compose and execute multiple feature plugins in sequence.

    This class provides a pipeline for orchestrating the execution of
    multiple feature plugins. It handles:

    - Plugin ordering and execution
    - Feature name collision detection
    - Error handling and recovery
    - Execution metrics and timing
    - Input/output validation

    Example:
        ```python
        # Create pipeline from plugin instances
        pipeline = FeaturePipeline(
            plugins=[
                (temporal_plugin, {"include_cyclical": True}),
                (lag_plugin, {"lag_periods": [24, 48]}),
            ],
        )

        # Or create from registry names
        pipeline = FeaturePipeline.from_registry(
            steps=[
                PluginStep(plugin_name="temporal_features", config={}),
                PluginStep(plugin_name="lag_features", config={"lag_periods": [24]}),
            ],
        )

        # Execute pipeline
        result = pipeline.run(df)
        ```

    Attributes:
        config: Pipeline configuration.
        steps: List of (plugin, config) tuples to execute.
    """

    def __init__(
        self,
        plugins: Sequence[tuple[BaseFeaturePlugin, dict[str, Any]]] | None = None,
        config: PipelineConfig | None = None,
    ) -> None:
        """Initialize the feature pipeline.

        Args:
            plugins: Sequence of (plugin, config) tuples to execute.
            config: Pipeline configuration (defaults to PipelineConfig()).
        """
        self._steps: list[tuple[BaseFeaturePlugin, dict[str, Any]]] = []
        self._config = config or PipelineConfig()

        if plugins:
            for plugin, plugin_config in plugins:
                self.add_plugin(plugin, plugin_config)

    @classmethod
    def from_registry(
        cls,
        steps: Sequence[PluginStep],
        config: PipelineConfig | None = None,
        registry: PluginRegistry | None = None,
    ) -> FeaturePipeline:
        """Create a pipeline from registry plugin names.

        Args:
            steps: Sequence of PluginStep configurations.
            config: Pipeline configuration.
            registry: Plugin registry to use (defaults to global registry).

        Returns:
            Configured FeaturePipeline instance.

        Raises:
            PluginNotFoundError: If a plugin is not found in the registry.
        """
        reg = registry or PluginRegistry()
        plugins: list[tuple[BaseFeaturePlugin, dict[str, Any]]] = []

        for step in steps:
            if not step.enabled:
                continue

            plugin = reg.get_plugin(step.plugin_name)
            plugins.append((plugin, step.config))

        return cls(plugins=plugins, config=config)

    @property
    def config(self) -> PipelineConfig:
        """Get the pipeline configuration."""
        return self._config

    @property
    def plugin_count(self) -> int:
        """Get the number of plugins in the pipeline."""
        return len(self._steps)

    def add_plugin(
        self,
        plugin: BaseFeaturePlugin,
        config: dict[str, Any] | None = None,
    ) -> FeaturePipeline:
        """Add a plugin to the pipeline.

        Args:
            plugin: Plugin instance to add.
            config: Plugin-specific configuration.

        Returns:
            Self for method chaining.

        Raises:
            TypeError: If plugin is not a BaseFeaturePlugin instance.
        """
        if not isinstance(plugin, BaseFeaturePlugin):
            msg = f"Expected BaseFeaturePlugin, got {type(plugin)}"
            raise TypeError(msg)

        self._steps.append((plugin, config or {}))
        logger.debug(
            "Added plugin '%s' v%s to pipeline",
            plugin.name,
            plugin.version,
        )
        return self

    def remove_plugin(self, plugin_name: str) -> bool:
        """Remove a plugin from the pipeline by name.

        Args:
            plugin_name: Name of the plugin to remove.

        Returns:
            True if plugin was removed, False if not found.
        """
        for i, (plugin, _) in enumerate(self._steps):
            if plugin.name == plugin_name:
                self._steps.pop(i)
                logger.debug("Removed plugin '%s' from pipeline", plugin_name)
                return True
        return False

    def get_plugins(self) -> list[tuple[str, str]]:
        """Get list of plugins with their versions.

        Returns:
            List of (plugin_name, version) tuples.
        """
        return [(p.name, p.version) for p, _ in self._steps]

    def detect_feature_collisions(
        self,
        configs: Sequence[dict[str, Any]] | None = None,
    ) -> dict[str, list[str]]:
        """Detect feature name collisions across plugins.

        Args:
            configs: Optional list of configs corresponding to each plugin.
                If not provided, uses the stored configs.

        Returns:
            Dictionary mapping colliding feature names to list of plugin names.
        """
        feature_sources: dict[str, list[str]] = {}

        for i, (plugin, stored_config) in enumerate(self._steps):
            config = configs[i] if configs and i < len(configs) else stored_config
            feature_names = plugin.get_feature_names(config)

            for name in feature_names:
                if name not in feature_sources:
                    feature_sources[name] = []
                feature_sources[name].append(plugin.name)

        # Return only features with multiple sources
        return {name: sources for name, sources in feature_sources.items() if len(sources) > 1}

    def get_all_feature_names(
        self,
        configs: Sequence[dict[str, Any]] | None = None,
    ) -> list[str]:
        """Get all feature names that will be generated.

        Args:
            configs: Optional list of configs corresponding to each plugin.

        Returns:
            List of all feature names (may contain duplicates if collisions exist).
        """
        all_features: list[str] = []

        for i, (plugin, stored_config) in enumerate(self._steps):
            config = configs[i] if configs and i < len(configs) else stored_config
            all_features.extend(plugin.get_feature_names(config))

        return all_features

    def validate(self) -> list[str]:
        """Validate the pipeline configuration.

        Returns:
            List of validation error messages (empty if valid).
        """
        errors: list[str] = []

        if not self._steps:
            errors.append("Pipeline has no plugins configured")

        # Check for feature collisions
        if self._config.detect_collisions:
            collisions = self.detect_feature_collisions()
            if collisions:
                for name, plugins in collisions.items():
                    errors.append(
                        f"Feature '{name}' is generated by multiple plugins: "
                        f"{', '.join(plugins)}"
                    )

        # Validate each plugin's config
        for plugin, config in self._steps:
            try:
                plugin.validate_config(config)
            except ValueError as e:
                errors.append(f"Plugin '{plugin.name}' config error: {e}")

        return errors

    def run(
        self,
        df: pd.DataFrame,
        override_configs: dict[str, dict[str, Any]] | None = None,
    ) -> PipelineResult:
        """Execute the pipeline on the input DataFrame.

        Args:
            df: Input DataFrame with timestamp index.
            override_configs: Optional dict mapping plugin names to config
                overrides.

        Returns:
            PipelineResult containing output DataFrame and execution metadata.

        Raises:
            PipelineConfigError: If pipeline validation fails.
            PipelineExecutionError: If execution fails and fail_fast is True.
            FeatureCollisionError: If feature collisions are detected.
        """
        start_time = time.perf_counter()
        override_configs = override_configs or {}

        # Validate pipeline configuration
        validation_errors = self.validate()
        if validation_errors:
            # Only raise if detect_collisions is True for collision errors
            non_collision_errors = [
                e for e in validation_errors if "generated by multiple plugins" not in e
            ]
            if non_collision_errors:
                msg = f"Pipeline validation failed: {'; '.join(non_collision_errors)}"
                raise PipelineConfigError(msg)

            if self._config.detect_collisions:
                collisions = self.detect_feature_collisions()
                if collisions:
                    raise FeatureCollisionError(collisions)

        # Prepare working DataFrame
        working_df = df.copy() if self._config.copy_input else df
        input_columns = set(working_df.columns)
        input_rows = len(working_df)

        all_feature_names: list[str] = []
        plugin_results: list[PluginExecutionResult] = []
        success = True

        # Execute each plugin
        for plugin, stored_config in self._steps:
            plugin_config = {**stored_config, **override_configs.get(plugin.name, {})}
            plugin_start = time.perf_counter()

            try:
                # Validate plugin config
                plugin.validate_config(plugin_config)

                # Generate features
                working_df = plugin.generate_features(working_df, plugin_config)

                # Get generated feature names
                feature_names = plugin.get_feature_names(plugin_config)
                all_feature_names.extend(feature_names)

                plugin_time = (time.perf_counter() - plugin_start) * 1000

                plugin_results.append(
                    PluginExecutionResult(
                        plugin_name=plugin.name,
                        plugin_version=plugin.version,
                        feature_names=feature_names,
                        execution_time_ms=plugin_time,
                        rows_processed=len(working_df),
                        success=True,
                    )
                )

                logger.debug(
                    "Plugin '%s' generated %d features in %.2fms",
                    plugin.name,
                    len(feature_names),
                    plugin_time,
                )

            except Exception as e:
                plugin_time = (time.perf_counter() - plugin_start) * 1000
                error_msg = str(e)

                plugin_results.append(
                    PluginExecutionResult(
                        plugin_name=plugin.name,
                        plugin_version=plugin.version,
                        feature_names=[],
                        execution_time_ms=plugin_time,
                        rows_processed=0,
                        success=False,
                        error_message=error_msg,
                    )
                )

                logger.error(
                    "Plugin '%s' failed: %s",
                    plugin.name,
                    error_msg,
                )

                if self._config.fail_fast:
                    success = False
                    msg = f"Plugin '{plugin.name}' failed: {error_msg}"
                    raise PipelineExecutionError(
                        msg,
                        plugin_name=plugin.name,
                        stage="execution",
                    ) from e

                success = False

        # Remove input columns if not preserving
        if not self._config.preserve_input_columns:
            columns_to_keep = [c for c in working_df.columns if c not in input_columns]
            working_df = working_df[columns_to_keep]

        total_time = (time.perf_counter() - start_time) * 1000

        result = PipelineResult(
            df=working_df,
            feature_names=all_feature_names,
            plugin_results=plugin_results,
            execution_time_ms=total_time,
            input_rows=input_rows,
            output_columns=len(working_df.columns),
            plugins_executed=sum(1 for r in plugin_results if r.success),
            success=success,
        )

        logger.info(
            "Pipeline executed: %d plugins, %d features, %.2fms",
            result.plugins_executed,
            len(result.feature_names),
            result.execution_time_ms,
        )

        return result

    def __repr__(self) -> str:
        """Return string representation of the pipeline.

        Returns:
            String showing the number of plugins in the pipeline.
        """
        plugin_names = [p.name for p, _ in self._steps]
        return f"FeaturePipeline(plugins={plugin_names})"

    def __len__(self) -> int:
        """Return the number of plugins in the pipeline."""
        return len(self._steps)
